language: cpp
sudo: required
dist: trusty
os: linux

matrix:
  include:
    # Clang 5.0
    - env: COMPILER=clang++-5.0
      addons: &defaults { apt: { packages: ["clang-5.0", "valgrind"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-5.0"] } }

   # GCC 7
   - env: COMPILER=g++-7
     addons: { apt: { packages: ["g++-7", "valgrind"], sources: ["ubuntu-toolchain-r-test"] } }


#addons:
#  apt:
#   sources:
#      - ubuntu-toolchain-r-test
#      - llvm-toolchain-trusty-5.0
#   packages:
#      - valgrind
#      - libboost-all-dev
#      - gcc-7
#      - clang-5.0

before_install:
 # Install a supported cmake version (>= 3.4.3)
  - wget -O cmake.sh https://cmake.org/files/v3.11/cmake-3.11.0-rc1-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
  - pip install --user cpp-coveralls
  - git clone https://github.com/google/googletest
  - cd googletest
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ..
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make