dist: artful
language: cpp

sudo: required
addons:
  apt:
   sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0

   packages:
      - valgrind
      - libboost-all-dev
      - gcc-7
      - clang-5.0

before_install:
  - pip install --user cpp-coveralls
  - git clone https://github.com/google/googletest
  - cd googletest
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ..
  - cd ..

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make